[2025-05-06T09:25:03.711+0000] {processor.py:157} INFO - Started process (PID=2891) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:25:03.711+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:25:03.712+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:25:03.712+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:25:03.716+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:25:03.715+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:25:03.716+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:25:03.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.030 seconds
[2025-05-06T09:25:34.097+0000] {processor.py:157} INFO - Started process (PID=2939) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:25:34.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:25:34.101+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:25:34.100+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:25:34.107+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:25:34.105+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:25:34.107+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:25:34.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.046 seconds
[2025-05-06T09:26:04.418+0000] {processor.py:157} INFO - Started process (PID=2980) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:26:04.420+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:26:04.421+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:26:04.420+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:26:04.423+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:26:04.423+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:26:04.424+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:26:04.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.027 seconds
[2025-05-06T09:26:34.768+0000] {processor.py:157} INFO - Started process (PID=3029) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:26:34.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:26:34.773+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:26:34.773+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:26:34.783+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:26:34.780+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:26:34.784+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:26:34.810+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.047 seconds
[2025-05-06T09:27:05.173+0000] {processor.py:157} INFO - Started process (PID=3078) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:27:05.175+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:27:05.175+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:27:05.175+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:27:05.179+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:27:05.178+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:27:05.179+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:27:05.201+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.031 seconds
[2025-05-06T09:27:35.556+0000] {processor.py:157} INFO - Started process (PID=3119) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:27:35.558+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:27:35.558+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:27:35.558+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:27:35.561+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:27:35.560+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:27:35.562+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:27:35.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.025 seconds
[2025-05-06T09:28:05.843+0000] {processor.py:157} INFO - Started process (PID=3168) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:28:05.845+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:28:05.845+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:28:05.845+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:28:05.847+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:28:05.847+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:28:05.848+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:28:05.862+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.021 seconds
[2025-05-06T09:28:36.179+0000] {processor.py:157} INFO - Started process (PID=3209) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:28:36.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:28:36.182+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:28:36.182+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:28:36.185+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:28:36.184+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:28:36.186+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:28:36.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.031 seconds
[2025-05-06T09:29:06.519+0000] {processor.py:157} INFO - Started process (PID=3257) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:29:06.521+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:29:06.521+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:29:06.521+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:29:06.525+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:29:06.524+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:29:06.526+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:29:06.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.032 seconds
[2025-05-06T09:29:36.863+0000] {processor.py:157} INFO - Started process (PID=3306) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:29:36.865+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:29:36.866+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:29:36.865+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:29:36.869+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:29:36.868+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:29:36.869+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:29:36.888+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.028 seconds
[2025-05-06T09:30:07.217+0000] {processor.py:157} INFO - Started process (PID=3347) to work on /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:30:07.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/example_dag.py.py for tasks to queue
[2025-05-06T09:30:07.219+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:30:07.219+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:30:07.222+0000] {logging_mixin.py:151} INFO - [2025-05-06T09:30:07.221+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/example_dag.py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py.py", line 5, in <module>
    from airflow.providers.apache.hdfs.hooks.hdfs import HDFSHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-05-06T09:30:07.223+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py.py
[2025-05-06T09:30:07.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/example_dag.py.py took 0.030 seconds
