[2025-05-05T22:33:03.864+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movielens_ingestion.download_movielens_data manual__2025-05-05T22:33:02.097910+00:00 [queued]>
[2025-05-05T22:33:03.870+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movielens_ingestion.download_movielens_data manual__2025-05-05T22:33:02.097910+00:00 [queued]>
[2025-05-05T22:33:03.870+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-05T22:33:03.881+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): download_movielens_data> on 2025-05-05 22:33:02.097910+00:00
[2025-05-05T22:33:03.887+0000] {standard_task_runner.py:57} INFO - Started process 209 to run task
[2025-05-05T22:33:03.889+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movielens_ingestion', 'download_movielens_data', 'manual__2025-05-05T22:33:02.097910+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/movielens_ingestion.py', '--cfg-path', '/tmp/tmprx0fyax2']
[2025-05-05T22:33:03.893+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask download_movielens_data
[2025-05-05T22:33:03.904+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-05T22:33:03.929+0000] {task_command.py:415} INFO - Running <TaskInstance: movielens_ingestion.download_movielens_data manual__2025-05-05T22:33:02.097910+00:00 [running]> on host 56aa4ba7abee
[2025-05-05T22:33:03.992+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movielens_ingestion' AIRFLOW_CTX_TASK_ID='download_movielens_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T22:33:02.097910+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T22:33:02.097910+00:00'
[2025-05-05T22:33:04.004+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movielens_ingestion.py", line 28, in download_movielens_data
    subprocess.run(['wget', '-O', zip_path, base_url], check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'wget'
[2025-05-05T22:33:04.013+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=movielens_ingestion, task_id=download_movielens_data, execution_date=20250505T223302, start_date=20250505T223303, end_date=20250505T223304
[2025-05-05T22:33:04.024+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task download_movielens_data ([Errno 13] Permission denied: 'wget'; 209)
[2025-05-05T22:33:04.061+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-05T22:33:04.085+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
