[2025-05-05T22:53:56.342+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-05T22:48:49.443106+00:00 [queued]>
[2025-05-05T22:53:56.351+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-05T22:48:49.443106+00:00 [queued]>
[2025-05-05T22:53:56.351+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-05-05T22:53:56.364+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): upload_to_hdfs> on 2025-05-05 22:48:49.443106+00:00
[2025-05-05T22:53:56.370+0000] {standard_task_runner.py:57} INFO - Started process 874 to run task
[2025-05-05T22:53:56.373+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movielens_ingestion', 'upload_to_hdfs', 'manual__2025-05-05T22:48:49.443106+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/movielens_ingestion.py', '--cfg-path', '/tmp/tmpofhn7vwl']
[2025-05-05T22:53:56.374+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask upload_to_hdfs
[2025-05-05T22:53:56.390+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-05T22:53:56.419+0000] {task_command.py:415} INFO - Running <TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-05T22:48:49.443106+00:00 [running]> on host 56aa4ba7abee
[2025-05-05T22:53:56.497+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movielens_ingestion' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T22:48:49.443106+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T22:48:49.443106+00:00'
[2025-05-05T22:53:56.499+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movielens_ingestion.py", line 44, in upload_to_hdfs
    webhdfs_hook.mkdir(hdfs_path)
AttributeError: 'WebHDFSHook' object has no attribute 'mkdir'
[2025-05-05T22:53:56.506+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=movielens_ingestion, task_id=upload_to_hdfs, execution_date=20250505T224849, start_date=20250505T225356, end_date=20250505T225356
[2025-05-05T22:53:56.522+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task upload_to_hdfs ('WebHDFSHook' object has no attribute 'mkdir'; 874)
[2025-05-05T22:53:56.544+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-05T22:53:56.567+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
